name: 'Bunkai SCA'
description: 'A minimalist, dependency-aware Software Composition Analysis (SCA) tool for Perl.'
author: 'LESIS'
branding:
  icon: "shield"
  color: "blue"

inputs:
  perl-version:
    description: 'The version of Perl to use.'
    required: false
    default: '5.42'
  project-path:
    description: 'The path to the project to be analyzed by Bunkai.'
    required: false
    default: '.'
  perlcritic-severity:
    description: 'The severity level for Perl::Critic.'
    required: false
    default: '1'
  perlcritic-paths:
    description: 'The paths to lint with Perl::Critic.'
    required: false
    default: 'lib bunkai.pl'
  sarif-output:
    description: 'The SARIF output file path.'
    required: false
    default: ''
  test-command:
    description: 'The command to run tests with coverage.'
    required: false
    default: |
      PERL5OPT=-MDevel::Cover=-db,coverage_db,-silent,1 prove -lvr tests/
      cover -report text
      cover -test

runs:
  using: "composite"
  steps:
    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ inputs.perl-version }}

    - name: Install Dependencies
      shell: bash
      run: cpanm --installdeps --with-develop ${{ github.action_path }}

    - name: Lint with Perl::Critic
      shell: bash
      run: perlcritic --severity ${{ inputs.perlcritic-severity }} ${{ inputs.perlcritic-paths }}

    - name: Test with Coverage
      shell: bash
      run: ${{ inputs.test-command }}

    - name: Run Bunkai
      shell: bash
      run: |
        if [ -n "${{ inputs.sarif-output }}" ]; then
          perl ${{ github.action_path }}/bunkai.pl --path ${{ inputs.project-path }} --sarif ${{ inputs.sarif-output }}
          exit 0
        fi
        perl ${{ github.action_path }}/bunkai.pl --path ${{ inputs.project-path }}
