# .github/workflows/bunkai.yml

name: Bunkai CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version: [ '5.32', '5.34', '5.36' ]
    name: Perl ${{ matrix.perl-version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install Dependencies
        run: cpanm --installdeps --with-develop .

      - name: Lint with Perl::Critic
        run: perlcritic --severity 1 lib bunkai.pl

      - name: Test with Coverage
        run: |
          PERL5OPT=-MDevel::Cover=-db,coverage_db,-silent,1 prove -lvr tests/
          cover -report text
          cover -test

      - name: Run Bunkai on an example project
        run: |
          mkdir -p example_project
          echo "requires 'Plack', '==1.0048';" > example_project/cpanfile
          echo "requires 'Dancer2';" >> example_project/cpanfile
          perl bunkai.pl --path ./example_project