name: 'Bunkai SCA'
description: 'A minimalist, dependency-aware Software Composition Analysis (SCA) tool for Perl.'
author: 'LESIS'
branding:
  icon: "shield"
  color: "blue"

inputs:
  project-path:
    description: 'The path to the project to be analyzed by Bunkai.'
    required: false
    default: '.'
  perlcritic-severity:
    description: 'The severity level for Perl::Critic.'
    required: false
    default: '1'
  perlcritic-paths:
    description: 'The paths to lint with Perl::Critic.'
    required: false
    default: 'lib bunkai.pl'
  sarif-output:
    description: 'The SARIF output file path.'
    required: false
    default: ''
  test-command:
    description: 'The command to run tests with coverage.'
    required: false
    default: |
      PERL5OPT=-MDevel::Cover=-db,coverage_db,-silent,1 prove -lvr tests/
      cover -report text
      cover -test

runs:
  using: docker
  image: docker://ghcr.io/lesis-lat/bunkai/bunkai:latest
  entrypoint: /app/action-entrypoint.sh
